### ISSUE TITLE
验证已符合要求，但是下一步就出现404错误了。请看图片。

### ISSUE THREAD

**Issue by lvvfa** [CN-Scars/A-Magisk-module-that-can-change-model-to-Google-Pixel-7-Pro#2]
![Screenshot_2023-02-02-07-48-06-073_com google android apps subscriptions red](https://user-images.githubusercontent.com/96319746/216193934-df5aff1c-cab8-4671-98c1-250cf1212422.jpg)

**Comment by CN-Scars** [comment]
您好，造成图片当中的问题更像是您的网络代理或者Google套件出现了问题，建议检查您的代理的可用状态以及代理和Google套件是否正确配置，该Magisk模块只会更改机型，与该模块无关
