### ISSUE TITLE
机型识别成功

### ISSUE THREAD

**Issue by Tylxer** [CN-Scars/A-Magisk-module-that-can-change-model-to-Google-Pixel-7-Pro#3]
用google one有免费使用vpn的选项，但是实际无法连接，理论上应该不会测试账号吧？能否提供一下机型的完整资料

**Comment by CN-Scars** [comment]
该Magisk模块不保证能够像一些第三方ROM一样能够更加底层地模拟机型，若您有兴趣，我可以给您提供目前Google Pixel 7 Pro最新的system.prop，以下是该文件的内容：
```
###
# begin product/etc/build.prop
###

# begin common build properties
ro.product.product.brand=google
ro.product.product.device=cheetah
ro.product.product.manufacturer=Google
ro.product.product.model=Pixel 7 Pro
ro.product.product.name=cheetah
ro.product.build.date=Wed Nov 23 21:54:03 UTC 2022
ro.product.build.date.utc=1669240443
ro.product.build.fingerprint=google/cheetah/cheetah:13/TQ1A.230105.002/9325679:user/release-keys
ro.product.build.id=TQ1A.230105.002
ro.product.build.tags=release-keys
ro.product.build.type=user
ro.product.build.version.incremental=9325679
ro.product.build.version.release=13
ro.product.build.version.release_or_codename=13
ro.product.build.version.sdk=33
# end common build properties

# begin PRODUCT_PRODUCT_PROPERTIES
ro.support_one_handed_mode=true
ro.charger.enable_suspend=true
ro.opa.eligible_device=true
ro.com.google.ime.bs_theme=true
ro.com.google.ime.theme_id=5
ro.com.google.ime.system_lm_dir=/product/usr/share/ime/google/d3_lms
# end PRODUCT_PRODUCT_PROPERTIES

###
# end product/etc/build.prop
###

###
#-#
###

###
# begin vendor/build.prop
###

# begin common build properties
ro.product.vendor.brand=google
ro.product.vendor.device=cheetah
ro.product.vendor.manufacturer=Google
ro.product.vendor.model=Pixel 7 Pro
ro.product.vendor.name=cheetah
ro.vendor.build.date=Wed Nov 23 21:54:03 UTC 2022
ro.vendor.build.date.utc=1669240443
ro.vendor.build.fingerprint=google/cheetah/cheetah:13/TQ1A.230105.002/9325679:user/release-keys
ro.vendor.build.id=TQ1A.230105.002
ro.vendor.build.tags=release-keys
ro.vendor.build.type=user
ro.vendor.build.version.incremental=9325679
ro.vendor.build.version.release=13
ro.vendor.build.version.release_or_codename=13
ro.vendor.build.version.sdk=33
# end common build properties

# begin ADDITIONAL_VENDOR_PROPERTIES
ro.vendor.build.security_patch=2023-01-05
# end ADDITIONAL_VENDOR_PROPERTIES

# begin BOOTIMAGE_build_prop to_system_propERTIES
ro.bootimage.build.date=Wed Nov 23 21:54:03 UTC 2022
ro.bootimage.build.date.utc=1669240443
ro.bootimage.build.fingerprint=google/cheetah/cheetah:13/TQ1A.230105.002/9325679:user/release-keys
# end BOOTIMAGE_build_prop to_system_propERTIES

# begin PRODUCT_PROPERTY_OVERRIDES
persist.rcs.supported=1
persist.sysui.monet=true
# end PRODUCT_PROPERTY_OVERRIDES

###
# end vendor/build.prop
###

###
#-#
###

###
# begin vendor/odm/etc/build.prop
###

# begin common build properties
ro.product.odm.brand=google
ro.product.odm.device=cheetah
ro.product.odm.manufacturer=Google
ro.product.odm.model=Pixel 7 Pro
ro.product.odm.name=cheetah
ro.odm.build.date=Wed Nov 23 21:54:03 UTC 2022
ro.odm.build.date.utc=1669240443
ro.odm.build.fingerprint=google/cheetah/cheetah:13/TQ1A.230105.002/9325679:user/release-keys
ro.odm.build.id=TQ1A.230105.002
ro.odm.build.tags=release-keys
ro.odm.build.type=user
ro.odm.build.version.incremental=9325679
ro.odm.build.version.release=13
ro.odm.build.version.release_or_codename=13
ro.odm.build.version.sdk=33
# end common build properties

###
# end vendor/odm/etc/build.prop
###

###
#-#
###

###
# begin system/system/build.prop
###

# begin common build properties
ro.product.system.brand=google
ro.product.system.device=generic
ro.product.system.manufacturer=Google
ro.product.system.model=mainline
ro.product.system.name=mainline
ro.system.build.date=Wed Nov 23 21:54:03 UTC 2022
ro.system.build.date.utc=1669240443
ro.system.build.fingerprint=google/cheetah/cheetah:13/TQ1A.230105.002/9325679:user/release-keys
ro.system.build.id=TQ1A.230105.002
ro.system.build.tags=release-keys
ro.system.build.type=user
ro.system.build.version.incremental=9325679
ro.system.build.version.release=13
ro.system.build.version.release_or_codename=13
ro.system.build.version.sdk=33
# end common build properties

# begin build properties
ro.build.id=TQ1A.230105.002
ro.build.display.id=TQ1A.230105.002
ro.build.version.incremental=9325679
ro.build.version.sdk=33
ro.build.version.release=13
ro.build.version.release_or_codename=13
ro.build.version.security_patch=2023-01-05
ro.build.date=Wed Nov 23 21:54:03 UTC 2022
ro.build.date.utc=1669240443
ro.build.type=user
ro.build.user=android-build
ro.build.host=abfarm-release-rbe-64-2004-0069
ro.build.tags=release-keys
ro.build.flavor=cheetah-user
ro.build.product=cheetah
ro.build.description=cheetah-user 13 TQ1A.230105.002 9325679 release-keys
# end build properties

# begin extra's from /system/build.prop
ro.build.fingerprint=google/cheetah/cheetah:13/TQ1A.230105.002/9325679:user/release-keys
ro.product.brand=google
ro.product.device=cheetah
ro.product.manufacturer=Google
ro.product.model=Pixel 7 Pro
ro.product.name=cheetah
# end extra's from /system/build.prop

###
# end system/system/build.prop
###

###
#-#
###

###
# begin system_ext/etc/build.prop
###

# begin common build properties
ro.product.system_ext.brand=google
ro.product.system_ext.device=cheetah
ro.product.system_ext.manufacturer=Google
ro.product.system_ext.model=Pixel 7 Pro
ro.product.system_ext.name=cheetah
ro.system_ext.build.date=Wed Nov 23 21:54:03 UTC 2022
ro.system_ext.build.date.utc=1669240443
ro.system_ext.build.fingerprint=google/cheetah/cheetah:13/TQ1A.230105.002/9325679:user/release-keys
ro.system_ext.build.id=TQ1A.230105.002
ro.system_ext.build.tags=release-keys
ro.system_ext.build.type=user
ro.system_ext.build.version.incremental=9325679
ro.system_ext.build.version.release=13
ro.system_ext.build.version.release_or_codename=13
ro.system_ext.build.version.sdk=33
# end common build properties

###
# end system_ext/etc/build.prop
###
```

**Comment by Tylxer** [comment]
> 该Magisk模块不保证能够像一些第三方ROM一样能够更加底层地模拟机型，若您有兴趣，我可以给您提供目前Google Pixel 7 Pro最新的system.prop，以下是该文件的内容：
> 
> ```
> ###
> # begin product/etc/build.prop
> ###
> 
> # begin common build properties
> ro.product.product.brand=google
> ro.product.product.device=cheetah
> ro.product.product.manufacturer=Google
> ro.product.product.model=Pixel 7 Pro
> ro.product.product.name=cheetah
> ro.product.build.date=Wed Nov 23 21:54:03 UTC 2022
> ro.product.build.date.utc=1669240443
> ro.product.build.fingerprint=google/cheetah/cheetah:13/TQ1A.230105.002/9325679:user/release-keys
> ro.product.build.id=TQ1A.230105.002
> ro.product.build.tags=release-keys
> ro.product.build.type=user
> ro.product.build.version.incremental=9325679
> ro.product.build.version.release=13
> ro.product.build.version.release_or_codename=13
> ro.product.build.version.sdk=33
> # end common build properties
> 
> # begin PRODUCT_PRODUCT_PROPERTIES
> ro.support_one_handed_mode=true
> ro.charger.enable_suspend=true
> ro.opa.eligible_device=true
> ro.com.google.ime.bs_theme=true
> ro.com.google.ime.theme_id=5
> ro.com.google.ime.system_lm_dir=/product/usr/share/ime/google/d3_lms
> # end PRODUCT_PRODUCT_PROPERTIES
> 
> ###
> # end product/etc/build.prop
> ###
> 
> ###
> #-#
> ###
> 
> ###
> # begin vendor/build.prop
> ###
> 
> # begin common build properties
> ro.product.vendor.brand=google
> ro.product.vendor.device=cheetah
> ro.product.vendor.manufacturer=Google
> ro.product.vendor.model=Pixel 7 Pro
> ro.product.vendor.name=cheetah
> ro.vendor.build.date=Wed Nov 23 21:54:03 UTC 2022
> ro.vendor.build.date.utc=1669240443
> ro.vendor.build.fingerprint=google/cheetah/cheetah:13/TQ1A.230105.002/9325679:user/release-keys
> ro.vendor.build.id=TQ1A.230105.002
> ro.vendor.build.tags=release-keys
> ro.vendor.build.type=user
> ro.vendor.build.version.incremental=9325679
> ro.vendor.build.version.release=13
> ro.vendor.build.version.release_or_codename=13
> ro.vendor.build.version.sdk=33
> # end common build properties
> 
> # begin ADDITIONAL_VENDOR_PROPERTIES
> ro.vendor.build.security_patch=2023-01-05
> # end ADDITIONAL_VENDOR_PROPERTIES
> 
> # begin BOOTIMAGE_build_prop to_system_propERTIES
> ro.bootimage.build.date=Wed Nov 23 21:54:03 UTC 2022
> ro.bootimage.build.date.utc=1669240443
> ro.bootimage.build.fingerprint=google/cheetah/cheetah:13/TQ1A.230105.002/9325679:user/release-keys
> # end BOOTIMAGE_build_prop to_system_propERTIES
> 
> # begin PRODUCT_PROPERTY_OVERRIDES
> persist.rcs.supported=1
> persist.sysui.monet=true
> # end PRODUCT_PROPERTY_OVERRIDES
> 
> ###
> # end vendor/build.prop
> ###
> 
> ###
> #-#
> ###
> 
> ###
> # begin vendor/odm/etc/build.prop
> ###
> 
> # begin common build properties
> ro.product.odm.brand=google
> ro.product.odm.device=cheetah
> ro.product.odm.manufacturer=Google
> ro.product.odm.model=Pixel 7 Pro
> ro.product.odm.name=cheetah
> ro.odm.build.date=Wed Nov 23 21:54:03 UTC 2022
> ro.odm.build.date.utc=1669240443
> ro.odm.build.fingerprint=google/cheetah/cheetah:13/TQ1A.230105.002/9325679:user/release-keys
> ro.odm.build.id=TQ1A.230105.002
> ro.odm.build.tags=release-keys
> ro.odm.build.type=user
> ro.odm.build.version.incremental=9325679
> ro.odm.build.version.release=13
> ro.odm.build.version.release_or_codename=13
> ro.odm.build.version.sdk=33
> # end common build properties
> 
> ###
> # end vendor/odm/etc/build.prop
> ###
> 
> ###
> #-#
> ###
> 
> ###
> # begin system/system/build.prop
> ###
> 
> # begin common build properties
> ro.product.system.brand=google
> ro.product.system.device=generic
> ro.product.system.manufacturer=Google
> ro.product.system.model=mainline
> ro.product.system.name=mainline
> ro.system.build.date=Wed Nov 23 21:54:03 UTC 2022
> ro.system.build.date.utc=1669240443
> ro.system.build.fingerprint=google/cheetah/cheetah:13/TQ1A.230105.002/9325679:user/release-keys
> ro.system.build.id=TQ1A.230105.002
> ro.system.build.tags=release-keys
> ro.system.build.type=user
> ro.system.build.version.incremental=9325679
> ro.system.build.version.release=13
> ro.system.build.version.release_or_codename=13
> ro.system.build.version.sdk=33
> # end common build properties
> 
> # begin build properties
> ro.build.id=TQ1A.230105.002
> ro.build.display.id=TQ1A.230105.002
> ro.build.version.incremental=9325679
> ro.build.version.sdk=33
> ro.build.version.release=13
> ro.build.version.release_or_codename=13
> ro.build.version.security_patch=2023-01-05
> ro.build.date=Wed Nov 23 21:54:03 UTC 2022
> ro.build.date.utc=1669240443
> ro.build.type=user
> ro.build.user=android-build
> ro.build.host=abfarm-release-rbe-64-2004-0069
> ro.build.tags=release-keys
> ro.build.flavor=cheetah-user
> ro.build.product=cheetah
> ro.build.description=cheetah-user 13 TQ1A.230105.002 9325679 release-keys
> # end build properties
> 
> # begin extra's from /system/build.prop
> ro.build.fingerprint=google/cheetah/cheetah:13/TQ1A.230105.002/9325679:user/release-keys
> ro.product.brand=google
> ro.product.device=cheetah
> ro.product.manufacturer=Google
> ro.product.model=Pixel 7 Pro
> ro.product.name=cheetah
> # end extra's from /system/build.prop
> 
> ###
> # end system/system/build.prop
> ###
> 
> ###
> #-#
> ###
> 
> ###
> # begin system_ext/etc/build.prop
> ###
> 
> # begin common build properties
> ro.product.system_ext.brand=google
> ro.product.system_ext.device=cheetah
> ro.product.system_ext.manufacturer=Google
> ro.product.system_ext.model=Pixel 7 Pro
> ro.product.system_ext.name=cheetah
> ro.system_ext.build.date=Wed Nov 23 21:54:03 UTC 2022
> ro.system_ext.build.date.utc=1669240443
> ro.system_ext.build.fingerprint=google/cheetah/cheetah:13/TQ1A.230105.002/9325679:user/release-keys
> ro.system_ext.build.id=TQ1A.230105.002
> ro.system_ext.build.tags=release-keys
> ro.system_ext.build.type=user
> ro.system_ext.build.version.incremental=9325679
> ro.system_ext.build.version.release=13
> ro.system_ext.build.version.release_or_codename=13
> ro.system_ext.build.version.sdk=33
> # end common build properties
> 
> ###
> # end system_ext/etc/build.prop
> ###
> ```

多谢
